### ISSUE TITLE
NameError: name '_init_pyside_extension' is not defined

### ISSUE THREAD

**Issue by citypw** [radareorg/cutter-jupyter#12]
**Info**

* Ubuntu 20.04
* Python 3.8.2
* Cutter 1.12.0
* x86_64

**Log**
```
qt5ct: using qt5ct plugin
Plugins are loaded from "/home/pikey/.local/share/RadareOrg/Cutter/plugins"
Couldn't load module for plugin: "cutter_jupyter"
Traceback (most recent call last):
  File "/home/pikey/.local/share/RadareOrg/Cutter/plugins/python/cutter_jupyter/__init__.py", line 2, in <module>
    from . import plugin
  File "/home/pikey/.local/share/RadareOrg/Cutter/plugins/python/cutter_jupyter/plugin.py", line 3, in <module>
    from PySide2.QtWidgets import QAction
  File "/home/pikey/.local/lib/python3.8/site-packages/PySide2/__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "/home/pikey/.local/lib/python3.8/site-packages/PySide2/__init__.py", line 69, in _setupQtDirectories
    _init_pyside_extension()
NameError: name '_init_pyside_extension' is not defined
Loaded 1 plugin(s).
Plugins are loaded from "/usr/share/mate/RadareOrg/Cutter/plugins"
Plugins are loaded from "/home/pikey/.local/share/flatpak/exports/share/RadareOrg/Cutter/plugins"
Plugins are loaded from "/var/lib/flatpak/exports/share/RadareOrg/Cutter/plugins"
Plugins are loaded from "/usr/local/share/RadareOrg/Cutter/plugins"
Plugins are loaded from "/usr/share/RadareOrg/Cutter/plugins"
Plugins are loaded from "/var/lib/snapd/desktop/RadareOrg/Cutter/plugins"
qt5ct: D-Bus global menu: no
qt5ct: palette support is disabled
qt5ct: custom style sheet is disabled
```

**Comment by citypw** [comment]
**WORKAROUND**

Don't install pyside2* related libs via pip3 but:
```
sudo apt install python3-pyside2.qtwebenginewidgets python3-pyside2.qtwebenginecore python3-pyside2.qtwebengine
```

**Comment by dharmrajchauhan** [comment]
> **WORKAROUND**
> 
> Don't install pyside2* related libs via pip3 but:
> 
> ```
> sudo apt install python3-pyside2.qtwebenginewidgets python3-pyside2.qtwebenginecore python3-pyside2.qtwebengine
> ```
And what for windows machine..
i am using Anaconda environment i am download pyside2's 5.14 version
`pip install pYsIDE2==5.14 --user`

and i get Error like:- 
`NameError: name '_init_pyside_extension' is not defined`
